### ISSUE TITLE
Slack invite in README.md 'is no longer active'

### ISSUE THREAD

**Issue by mnuttall** [cdfoundation/meetups#2]
Hello, 
README.md in this repo includes a Slack invite link, https://join.slack.com/t/cdeliveryfdn/shared_invite/enQtNzk2OTgxNzY2NzkwLTQ3Zjg0OGJhZjdiMjlkMjZjZjJjN2EwZDg1Mjk3ODJkMzdmYjdmNTk0MWI2ZjI2MzgzNWExN2E3ZWExZGIyZDM. However Slack reports that 
> This invite link is no longer active.

making it currently impossible to join the CD Foundation Slack. Please can someone update the link?

**Comment by danlopez00** [comment]
updated
